In [84]:
import pandas as pd

In [126]:
def rte_tempo_join(data_rte_df, tempo_df, drop_last=False):
    if drop_last:
        tempo_df.drop(tempo_df.tail(1).index,inplace=True)

    #Format date
    data_rte_df["Date"] = pd.to_datetime(data_rte_df['Date'], format='%Y-%m-%d')
    tempo_df['Date'] =  pd.to_datetime(tempo_df['Date'], format='%Y-%m-%d %H:%M:%S')
    return pd.merge(data_rte_df, tempo_df, on="Date", how="left")

In [125]:
data_rte = pd.read_csv("clean_datasets/rte_production.csv").reset_index()

/tmp/ipykernel_10639/3893964724.py:1: DtypeWarning: Columns (18,19,20,21,22,26,27,30,31,33,36,37,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  data_rte = pd.read_csv("clean_datasets/rte_production.csv").reset_index()

In [87]:
tempo = pd.read_csv("clean_datasets/tempo_2014_2024.csv")

In [127]:
merge = rte_tempo_join(data_rte, tempo)
merge.to_csv("clean_datasets/rte_2014_2024.csv")

,index,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,...,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore,Type de jour TEMPO
0,0,France,Données définitives,2014-01-01,00:00,64660.0,63200,63200.0,454.0,0.0,...,2125,693.0,460,165.0,179.0,NaN,NaN,NaN,NaN,NaN
1,1,France,Données définitives,2014-01-01,00:30,63494.0,62100,61500.0,281.0,0.0,...,2450,495.0,592,170.0,181.0,NaN,NaN,NaN,NaN,NaN
2,2,France,Données définitives,2014-01-01,01:00,61362.0,59900,59900.0,281.0,0.0,...,2040,76.0,591,173.0,181.0,NaN,NaN,NaN,NaN,NaN
3,3,France,Données définitives,2014-01-01,01:30,61217.0,60600,60300.0,281.0,0.0,...,1849,0.0,595,174.0,180.0,NaN,NaN,NaN,NaN,NaN
4,4,France,Données définitives,2014-01-01,02:00,60748.0,59900,60200.0,281.0,0.0,...,1592,0.0,597,174.0,180.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180014,180014,France,Données temps réel,2024-04-08,10:45,49835.0,51200,50200.0,123.0,0.0,...,766,390.0,178,363.0,252.0,NaN,NaN,NaN,NaN,BLEU
180015,180015,France,Données temps réel,2024-04-08,11:15,50197.0,51250,50100.0,125.0,0.0,...,834,346.0,178,360.0,252.0,NaN,NaN,NaN,NaN,BLEU
180016,180016,France,Données temps réel,2024-04-08,11:45,50191.0,51700,50500.0,124.0,0.0,...,727,347.0,177,363.0,252.0,NaN,NaN,NaN,NaN,BLEU
180017,180017,France,Données temps réel,2024-04-08,12:15,50611.0,51500,50750.0,125.0,0.0,...,576,190.0,179,357.0,252.0,NaN,NaN,NaN,NaN,BLEU
180018,180018,France,Données temps réel,2024-04-08,12:45,50950.0,51650,51000.0,125.0,0.0,...,574,191.0,182,353.0,252.0,NaN,NaN,NaN,NaN,BLEU